### ISSUE TITLE
VRE-030 point 6: execution

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/Swarm-VRE#3]
Currently, it is only possible to execute software code via Notebooks and Python console but it is not possible to execute a script or any executable file via shell (e.g. from the Bash Terminal) even if the execute permission is applied to the file:

```sh
jovyan@jupyter-lmar76:~/other$ ls -l
total 12
-rw-r--r--  1 jovyan root 1648 Aug  7 09:23 Platform.ipynb
-rwxr-xr-x  1 jovyan root   24 Aug  7 15:28 test.sh
drwxr-xr-x 10 jovyan root 4096 Aug  7 09:20 VirES
jovyan@jupyter-lmar76:~/other$ ./test.sh
bash: ./test.sh: Permission denied
jovyan@jupyter-lmar76:~/other$
```

**Comment by pacesm** [comment]
I'll have a look on it.
Have you tried
```
$ /bin/bash ./test.sh
```
?

**Comment by smithara** [comment]
`bash test.sh`
and
`. test.sh` or `. ./test.sh`
both work for me, but, as you have found, just `./test.sh` doesn't work. ~~This is the normal behaviour with bash~~(edit) although I don't know why. Edit: might be something weird about the way JupyterHub works (I found that it worked fine on a locally running JupyterLab)

**Comment by pacesm** [comment]
The problem is that the NFS volume holding the home directories is mounted with `noexec` flag.

**Comment by lmar76** [comment]
I tried right now on the staging VRE and it works. On the operational one it is still not working.

**Comment by eox-cs1** [comment]
I just fixed this issue on the operational system as well, please try again.

**Comment by lmar76** [comment]
Tested, it works. Thank you.
