### ISSUE TITLE
Error while saving 04b1_Geomag-Models-eoxmagmod.ipynb

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/Swarm-VRE#9]
Issue detected no staging platform.

Trying to save the 04b1_Geomag-Models-eoxmagmod.ipynb notebook the following error message is displayed:

<img width="1552" alt="Screenshot 2020-03-26 at 16 09 01" src="https://user-images.githubusercontent.com/20207042/77662807-9edaf900-6f7c-11ea-9125-ca7a8191d7c7.png">

**Comment by pacesm** [comment]
I'll check it out. Probably some misconfiguration of nginx proxy on VRE staging/testing.

**Comment by pacesm** [comment]
I managed to reproduce the error on VRE-staging.
I also tested the same notebook on production VRE and I did not manage to reproduce the error there. From that I conclude that this error does not affect the production VRE.

**Comment by pacesm** [comment]
Solved by setting larger `client_max_body_size` parameter.

**Comment by pacesm** [comment]
@lmar76 please re-try

**Comment by lmar76** [comment]
It works. Thank you
